spring:
  profiles:
    active: local
  application:
    name: expenditure-diary
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 30000
      validation-timeout: 5000
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: ${JPA_VIEW_MODE}

jwt:
  secret_key: ${JWT_SECRET_KEY}

setting:
  twelveDataUrl: ${TWELVE_URL}
  twelveDataApiKey: ${TWELVE_API}

server:
  servlet:
    context-path: /expenditure-diary
  port: 8080

backend_server:
  web_url: ${UI_WEB_URL}
