spring:
  profiles:
    active: prod  # default to production

  datasource:
    primary:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${DB_HOST_PRIMARY}
      username: ${DB_USERNAME_PRIMARY}
      password: ${DB_PASSWORD_PRIMARY}
      hikari:
        maximum-pool-size: 10
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000

    secondary:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${DB_HOST_SECONDARY}
      username: ${DB_USERNAME_SECONDARY}
      password: ${DB_PASSWORD_SECONDARY}
      hikari:
        maximum-pool-size: 10
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: true
