spring:
#  profiles:
#    active: local
  application:
    name: expenditure-diary
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: ${JPA_VIEW_MODE}

backend_server:
  web_url: ${SERVER_URL}
  allow_register: ${ALLOW_REGISTER}

jwt:
  secret_key: ${JWT_SECRET_KEY}
  auth:
    users:
      admin_usr: ${ADMIN_USERNAME}
      admin_pwd: ${ADMIN_PASSWORD}

telegram:
  enable: ${TELEGRAM_BOT_ENABLE}
  bot-token: ${TELEGRAM_BOT_TOKEN}
  chat-id: ${TELEGRAM_CHAT_ID}

server:
  rate_limit: ${RATE_LIMIT}
  servlet:
    context-path: /expenditure-diary
  port: 8080

setting:
  enableSaveLog: ${ENABLE_SAVE_LOG}
  enableRegiser: ${ENABLE_REGISTER}


app:
  version: 1.0.10